version: "3"
services:
  kademliaNodes:
    image: testimage:latest
    stdin_open: true
    tty: true
    deploy:
      replicas: 100
#        resources:
#           limits:
#              cpus: "0.1"
#              memory: 50M
      restart_policy:
        condition: on-failure
        max_attempts: 2
#    ports:
#      - "4000:80"
    networks:
      - kademlia_network
      
networks:
  kademlia_network:
